apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-apps-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-apps/app-1
    repoURL: https://github.com/lazpuzzle/argocd-app-of-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true